.TH BLUEFISH "1" "December 2004" "Bluefish HTML editor" "User Commands"
.SH "NAME"
bluefish \- a powerful WYWIWYG HTML editor
.SH "SYNOPSIS"
.B bluefish
[\fIoptions\fR] [\fIfilename\fR]
.SH "DESCRIPTION"
.B bluefish
is a powerful WYWIWYG (What You Write Is What You Get) editor for
experienced web designers and programmers based on the GTK2 GUI interface.
It supports many programming and markup languages, but focuses on editing
dynamic and interactive websites.
.SH "OPTIONS"
Currently accepted options are:
.TP
\fB\-s\fR
Skip root check.
.TP
\fB\-v\fR
Show current version.
.TP
\fB\-n\fR
Open (file in) a new window.
.TP
\fB\-p \fIfilename\fR
Open the given project.
.TP
\fB\-h\fR
Show help screen.
.SH "SEE ALSO"
The programm is fully documented at
\fI\%http://bluefish.openoffice.nl/manual/\fR.
.SH "AUTHOR"
This manual page was written by \fBDavide Puricelli\fR <\&evo@debian.org\&>
for the Debian GNU/Linux system (but may be used by others) because the
original program does not have a manual page.
.PP
The manpage later was adopted and edited by the Bluefish Development Team.
