.\"     Title: bluefish\-unstable
.\"    Author: Daniel Leidert <daniel.leidert@wgdd.de>
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 11/25/2006
.\"    Manual: Bluefish Documentation
.\"    Source: Bluefish Editor 1.1
.\"
.TH "BLUEFISH\-UNSTABLE" "1" "11/25/2006" "Bluefish Editor 1.1" "Bluefish Documentation"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
bluefish\-unstable \- editor for experienced web designers and programmers
.SH "SYNOPSIS"
.HP 18
\fBbluefish\-unstable\fR [\fB\-s\fR | \fB\-\-skiprootcheck\fR] [\fB\-n\fR | \fB\-\-newwindow\fR] [\fB\-p\fR\ \fIPROJECTFILE\fR | \fB\-\-project=\fR\fB\fIPROJECTFILE\fR\fR] [\fIFILE(S)\fR...]
.HP 18
\fBbluefish\-unstable\fR {[\fB\-?\fR\ |\ \fB\-\-help\fR] | \fB\-\-help\-all\fR | \fB\-\-help\-*\fR | [\fB\-v\fR\ |\ \fB\-\-Version\fR]}
.SH "DESCRIPTION"
.PP

\fBbluefish\-unstable\fR
is an open\-source editor for experienced web designers and programmers, supporting many programming and markup languages, but focusing on creating dynamic and interactive websites.
.SH "OPTIONS"
.PP

\fBbluefish\-unstable\fR
currently supports the following options:
.PP
\fB\-n\fR, \fB\-\-newwindow\fR
.RS 3n
Open in a new window.
.RE
.PP
\fB\-p \fR\fB\fIPROJECTFILE\fR\fR, \fB\-\-project=\fR\fB\fIPROJECTFILE\fR\fR
.RS 3n
Open a project.
.RE
.PP
\fB\-s\fR, \fB\-\-skiprootcheck\fR
.RS 3n
Skip root check.
.RE
.PP
\fB\-?\fR, \fB\-\-help\fR
.RS 3n
Print application help screen.
.RE
.PP
\fB\-\-help\-*\fR, \fB\-\-help\-all\fR
.RS 3n
Print all or just a group of help options. These options are not documented here. Instead see
\fBgtk\-options\fR(7)
and
\fBgnome\-otions\fR(7).
.RE
.PP
\fB\-v\fR, \fB\-\-Version\fR
.RS 3n
Print version information.
.RE
.SH "SEE ALSO"
.PP

\fBgnome\-options\fR(7),
\fBgtk\-options\fR(7)
.SH "AUTHORS"
.PP
\fBDaniel Leidert\fR <\&daniel.leidert@wgdd.de\&>
.sp -1n
.IP "" 3n
Author and editor.
.PP
\fBMich\(`ele Garoche\fR <\&michele.garoche@easyconnect.fr\&>
.sp -1n
.IP "" 3n
Author.
.PP
\fBDavide Puricelli\fR <\&evo@debian.org\&>
.sp -1n
.IP "" 3n
Original author of the manpage written for the Debian system.

